---
name: Gillian McHugo
position: "Computational Biologist"
address: "School of Agriculture and Food Science, University College Dublin, Ireland"
www: gillianmchugo.github.io
email: "gillianmchugo@pm.me"
github: gillianmchugo
linkedin: gillianmchugo
orcid: 0000-0001-6920-0041
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 333333
aboutme: "Computational biology PhD researcher at University College Dublin studying integrative genomics of infectious diseases in cattle, focusing on trypanosomiasis in hybrid African cattle and bovine tuberculosis in Irish cattle."
output: 
  vitae::awesomecv:
  page_total: true
csl: "publications/apa-custom.csl"
---
```{r setup, include = F}
if (!require(knitr)) install.packages("knitr")
if (!require(tibble)) install.packages("tibble")
if (!require(vitae)) install.packages("vitae")
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```
# Education
```{r education}
tibble::tribble(~ Degree,
                ~ Year,
                ~ Institution,
                ~ Where,
                ~ details,
                "PhD in Infection Biology",
                "2018 - present",
                "University College Dublin",
                "Dublin, Ireland",
                "Computational biology PhD researcher at University College Dublin studying integrative genomics of infectious diseases in cattle, focusing on trypanosomiasis in hybrid African cattle and bovine tuberculosis in Irish cattle.",
                "MSc in Evolutionary Biology",
                "2015 - 2016",
                "University College Dublin",
                "Dublin, Ireland",
                "Thesis: A population genomic analysis of the endangered Galway sheep breed, published in \\href{https://doi.org/10.3389/fgene.2019.00927}{\\textit{Frontiers in Genetics} (DOI: 10.3389/fgene.2019.00927)}.",
                "BA (Mod) in Natural Sciences (Zoology)",
                "2011 - 2015",
                "Trinity College Dublin",
                "Dublin, Ireland",
                "Thesis: \\textit{Mytilus edulis} as a bioindicator of water pollution: potential histopathology biomarkers in Dublin Bay and Newquay, Co. Clare.") %>%
  vitae::detailed_entries(Institution,
                          Where,
                          Degree,
                          Year,
                          details,
                          .protect = F)
```
# Research Experience
```{r research}
tibble::tribble(~ Position,
                ~ Year,
                ~ Institution,
                ~ Where,
                "Research Assistant",
                "April - July, 2018",
                "Animal Genomics Laboratory,
                University College Dublin",
                "Dublin, Ireland",
                "Volunteer Research Assistant",
                "April - June, 2017",
                "Department of Behavioural Ecology and Evolutionary Genetics, Max Planck Institute of Ornithology",
                "Tenerife, Spain") %>%
  vitae::detailed_entries(Institution,
                          Where,
                          Position,
                          Year,
                          .protect = F)
```
# Publications
\fontsize{9pt}{1em}\bodyfontlight\upshape\color{text}
```{r publications}
vitae::bibliography_entries("publications/publications.bib") %>% 
  vitae::filter(type == "article-journal")
```
\footnotesize
A full list is available at [gillianmchugo.github.io](https://gillianmchugo.github.io) and [orcid.org/0000-0001-6920-0041](https://orcid.org/0000-0001-6920-0041)
  